spring.application.name=citasvet
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url: jdbc:postgresql://localhost:5433/citasvet_db
spring.datasource.username:citasvet
spring.datasource.password:citasvet123
spring.jpa.show-sql: true