spring.application.name=citasvet
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url: jdbc:postgresql://localhost:${DB_PORT:5433}/citasvet_db
spring.datasource.username:citasvet
spring.datasource.password:citasvet123
spring.jpa.show-sql: true
spring.config.import=optional:file:.env[.properties]